import type { Benefit, Region, Category } from './types'
import type { CommercialOffer } from '../../commercial/model/types'

export const mockRegions: Region[] = [
  { code: '14', name: 'Республика Саха (Якутия)' },
  { code: '77', name: 'Москва' },
  { code: '78', name: 'Санкт-Петербург' },
  { code: '54', name: 'Новосибирская область' },
]

export const mockCategories: Category[] = [
  { id: 1, name: 'Транспорт', slug: 'transport', icon: 'mdi:bus', description: 'Льготы на проезд' },
  { id: 2, name: 'Лекарства', slug: 'medicines', icon: 'mdi:pill', description: 'Льготы на лекарственные препараты' },
  { id: 3, name: 'ЖКХ', slug: 'utilities', icon: 'mdi:home', description: 'Компенсации за коммунальные услуги' },
  { id: 4, name: 'Компенсации', slug: 'compensations', icon: 'mdi:currency-rub', description: 'Денежные компенсации' },
  { id: 5, name: 'Покупки/магазины', slug: 'shopping', icon: 'mdi:shopping', description: 'Скидки в магазинах' },
  { id: 6, name: 'Соцподдержка', slug: 'social', icon: 'mdi:heart', description: 'Социальная поддержка' },
  { id: 7, name: 'Образование', slug: 'education', icon: 'mdi:school', description: 'Льготы на образование' },
  { id: 8, name: 'Услуги связи', slug: 'communication', icon: 'mdi:phone', description: 'Льготы на связь' },
]

export const mockBenefits: Benefit[] = [
  {
    id: 1,
    benefit_id: 'pens-transport-2025',
    title: 'Бесплатный проезд на общественном транспорте',
    description: 'Право на бесплатный проезд в городском и пригородном общественном транспорте для пенсионеров',
    benefit_type: 'federal',
    target_groups: ['pensioner', 'disability_1', 'disability_2'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    requirements: 'Наличие удостоверения льготника',
    how_to_get: 'Обратиться в МФЦ с паспортом и удостоверением. Подать заявление на получение социальной карты.',
    documents_needed: ['Паспорт', 'Удостоверение льготника', 'СНИЛС'],
    source_url: 'https://mintrud.gov.ru/social/benefits/transport',
    last_verified: '2024-12-01',
    categories: [mockCategories[0]],
    views_count: 1250,
    popularity_score: 8.5,
  },
  {
    id: 2,
    benefit_id: 'medicines-discount-2025',
    title: 'Льготное обеспечение лекарственными препаратами',
    description: 'Получение лекарственных препаратов по льготным ценам или бесплатно для льготных категорий граждан',
    benefit_type: 'federal',
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'disability_3', 'low_income'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие рецепта от врача и удостоверения льготника',
    how_to_get: 'Получить рецепт в поликлинике. Обратиться в аптеку с рецептом и удостоверением.',
    documents_needed: ['Рецепт врача', 'Удостоверение льготника', 'Паспорт'],
    source_url: 'https://mintrud.gov.ru/social/benefits/medicines',
    last_verified: '2024-11-15',
    categories: [mockCategories[1]],
    views_count: 2100,
    popularity_score: 9.2,
  },
  {
    id: 3,
    benefit_id: 'housing-compensation-2025',
    title: 'Компенсация расходов на оплату жилого помещения и коммунальных услуг',
    description: 'Частичная компенсация расходов на оплату жилья и коммунальных услуг для отдельных категорий граждан',
    benefit_type: 'federal',
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'veteran', 'low_income'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    requirements: 'Проживание в жилом помещении, расходы на ЖКУ превышают установленный процент от дохода',
    how_to_get: 'Подать заявление в органы социальной защиты населения по месту жительства с пакетом документов',
    documents_needed: ['Паспорт', 'Справка о доходах', 'Справка о составе семьи', 'Квитанции об оплате ЖКУ'],
    source_url: 'https://mintrud.gov.ru/social/benefits/housing',
    last_verified: '2024-12-10',
    categories: [mockCategories[2], mockCategories[3]],
    views_count: 1800,
    popularity_score: 8.8,
  },
  {
    id: 4,
    benefit_id: 'large-family-payment-2025',
    title: 'Ежемесячная денежная выплата многодетным семьям',
    description: 'Ежемесячная выплата семьям с тремя и более детьми',
    benefit_type: 'federal',
    target_groups: ['large_family'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие трех и более несовершеннолетних детей, среднедушевой доход семьи ниже прожиточного минимума',
    how_to_get: 'Обратиться в МФЦ или органы социальной защиты с заявлением и документами',
    documents_needed: ['Паспорта родителей', 'Свидетельства о рождении детей', 'Справка о доходах', 'Справка о составе семьи'],
    source_url: 'https://mintrud.gov.ru/social/benefits/large-family',
    last_verified: '2024-11-20',
    categories: [mockCategories[3], mockCategories[5]],
    views_count: 950,
    popularity_score: 7.5,
  },
  {
    id: 5,
    benefit_id: 'veteran-benefits-2025',
    title: 'Социальные льготы для ветеранов',
    description: 'Комплекс мер социальной поддержки для ветеранов Великой Отечественной войны и ветеранов боевых действий',
    benefit_type: 'federal',
    target_groups: ['veteran'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие удостоверения ветерана',
    how_to_get: 'Обратиться в органы социальной защиты с удостоверением ветерана',
    documents_needed: ['Удостоверение ветерана', 'Паспорт'],
    source_url: 'https://mintrud.gov.ru/social/benefits/veterans',
    last_verified: '2024-12-05',
    categories: [mockCategories[3], mockCategories[5]],
    views_count: 650,
    popularity_score: 7.0,
  },
  {
    id: 6,
    benefit_id: 'svo-participant-payment-2025',
    title: 'Ежемесячная денежная выплата участникам СВО',
    description: 'Ежемесячная выплата участникам специальной военной операции и членам их семей',
    benefit_type: 'federal',
    target_groups: ['svo_participant', 'svo_family'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Подтверждение участия в СВО или статус члена семьи участника СВО',
    how_to_get: 'Обратиться в военкомат или органы социальной защиты с документами',
    documents_needed: ['Документы, подтверждающие участие в СВО', 'Паспорт', 'Справка о составе семьи'],
    source_url: 'https://mintrud.gov.ru/social/benefits/svo',
    last_verified: '2024-12-01',
    categories: [mockCategories[3], mockCategories[5]],
    views_count: 420,
    popularity_score: 6.5,
  },
  {
    id: 7,
    benefit_id: 'low-income-help-2025',
    title: 'Социальная помощь малоимущим семьям',
    description: 'Предоставление различных видов социальной помощи семьям с доходом ниже прожиточного минимума',
    benefit_type: 'federal',
    target_groups: ['low_income'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    requirements: 'Среднедушевой доход семьи ниже прожиточного минимума, установленного в регионе',
    how_to_get: 'Подать заявление в органы социальной защиты с документами о доходах',
    documents_needed: ['Паспорта всех членов семьи', 'Справки о доходах', 'Справка о составе семьи'],
    source_url: 'https://mintrud.gov.ru/social/benefits/low-income',
    last_verified: '2024-11-25',
    categories: [mockCategories[3], mockCategories[5]],
    views_count: 1100,
    popularity_score: 7.8,
  },
  {
    id: 8,
    benefit_id: 'education-benefits-2025',
    title: 'Льготы при поступлении в образовательные учреждения',
    description: 'Преимущественное право при поступлении в вузы и ссузы для отдельных категорий граждан',
    benefit_type: 'federal',
    target_groups: ['disability_1', 'disability_2', 'veteran', 'large_family'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие удостоверения льготника, успешная сдача вступительных испытаний',
    how_to_get: 'При подаче документов в образовательное учреждение предъявить удостоверение льготника',
    documents_needed: ['Удостоверение льготника', 'Аттестат', 'Результаты ЕГЭ'],
    source_url: 'https://mintrud.gov.ru/social/benefits/education',
    last_verified: '2024-10-15',
    categories: [mockCategories[6]],
    views_count: 780,
    popularity_score: 7.2,
  },
  {
    id: 9,
    benefit_id: 'yakutia-cold-allowance-2025',
    title: 'Повышенная пенсия в связи с проживанием в районах Крайнего Севера',
    description: 'Дополнительные выплаты пенсионерам, проживающим в Республике Саха (Якутия)',
    benefit_type: 'regional',
    target_groups: ['pensioner'],
    regions: [mockRegions[0]],
    applies_to_all_regions: false,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Проживание на территории Республики Саха (Якутия), наличие пенсионного удостоверения',
    how_to_get: 'Обратиться в Пенсионный фонд по месту жительства с заявлением',
    documents_needed: ['Паспорт', 'Пенсионное удостоверение', 'Справка о регистрации по месту жительства'],
    source_url: 'https://pfr.gov.ru/yakutia/benefits',
    last_verified: '2024-12-01',
    categories: [mockCategories[3]],
    views_count: 320,
    popularity_score: 6.8,
  },
  {
    id: 10,
    benefit_id: 'yakutia-transport-2025',
    title: 'Льготный проезд в междугородном транспорте для жителей Якутии',
    description: 'Скидка на проезд в междугородном автобусном и железнодорожном транспорте для льготных категорий',
    benefit_type: 'regional',
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'large_family'],
    regions: [mockRegions[0]],
    applies_to_all_regions: false,
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    requirements: 'Наличие удостоверения льготника, регистрация в Республике Саха (Якутия)',
    how_to_get: 'При покупке билета предъявить удостоверение льготника в кассе',
    documents_needed: ['Удостоверение льготника', 'Паспорт'],
    source_url: 'https://yakutia.gov.ru/social/transport',
    last_verified: '2024-11-20',
    categories: [mockCategories[0]],
    views_count: 450,
    popularity_score: 7.0,
  },
  {
    id: 11,
    benefit_id: 'yakutia-medicines-2025',
    title: 'Дополнительное льготное лекарственное обеспечение в Якутии',
    description: 'Расширенный список лекарственных препаратов, предоставляемых по льготным ценам в Республике Саха',
    benefit_type: 'regional',
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'disability_3'],
    regions: [mockRegions[0]],
    applies_to_all_regions: false,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие рецепта от врача, регистрация в Республике Саха (Якутия)',
    how_to_get: 'Получить рецепт в поликлинике. Обратиться в аптеку с рецептом и удостоверением.',
    documents_needed: ['Рецепт врача', 'Удостоверение льготника', 'Паспорт'],
    source_url: 'https://yakutia.gov.ru/social/medicines',
    last_verified: '2024-12-05',
    categories: [mockCategories[1]],
    views_count: 380,
    popularity_score: 6.9,
  },
  {
    id: 12,
    benefit_id: 'yakutia-housing-2025',
    title: 'Компенсация расходов на отопление в Якутии',
    description: 'Дополнительная компенсация расходов на отопление для жителей Республики Саха (Якутия)',
    benefit_type: 'regional',
    target_groups: ['pensioner', 'disability_1', 'low_income'],
    regions: [mockRegions[0]],
    applies_to_all_regions: false,
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'expiring_soon',
    requirements: 'Проживание в Республике Саха (Якутия), расходы на отопление превышают установленный норматив',
    how_to_get: 'Подать заявление в органы социальной защиты с квитанциями об оплате',
    documents_needed: ['Паспорт', 'Квитанции об оплате отопления', 'Справка о доходах'],
    source_url: 'https://yakutia.gov.ru/social/housing',
    last_verified: '2024-11-15',
    categories: [mockCategories[2], mockCategories[3]],
    views_count: 290,
    popularity_score: 6.5,
  },
  {
    id: 13,
    benefit_id: 'municipal-yakutsk-transport-2025',
    title: 'Бесплатный проезд в городском транспорте Якутска',
    description: 'Бесплатный проезд в городском общественном транспорте для льготных категорий граждан в г. Якутск',
    benefit_type: 'municipal',
    target_groups: ['pensioner', 'disability_1', 'disability_2'],
    regions: [{ code: '14', name: 'г. Якутск' }],
    applies_to_all_regions: false,
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    requirements: 'Наличие удостоверения льготника, регистрация в г. Якутск',
    how_to_get: 'Обратиться в МФЦ г. Якутска с паспортом и удостоверением для получения проездного билета',
    documents_needed: ['Паспорт', 'Удостоверение льготника', 'Справка о регистрации в г. Якутск'],
    source_url: 'https://yakutsk-city.ru/social/transport',
    last_verified: '2024-12-01',
    categories: [mockCategories[0]],
    views_count: 520,
    popularity_score: 7.3,
  },
  {
    id: 14,
    benefit_id: 'communication-benefits-2025',
    title: 'Льготные тарифы на услуги связи',
    description: 'Специальные тарифы на телефонную связь и интернет для льготных категорий граждан',
    benefit_type: 'federal',
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'veteran'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие удостоверения льготника',
    how_to_get: 'Обратиться в офис оператора связи с удостоверением льготника для перехода на льготный тариф',
    documents_needed: ['Удостоверение льготника', 'Паспорт', 'Договор на услуги связи'],
    source_url: 'https://mintrud.gov.ru/social/benefits/communication',
    last_verified: '2024-11-10',
    categories: [mockCategories[7]],
    views_count: 640,
    popularity_score: 6.7,
  },
  {
    id: 15,
    benefit_id: 'disability-rehabilitation-2025',
    title: 'Технические средства реабилитации для инвалидов',
    description: 'Бесплатное предоставление технических средств реабилитации инвалидам',
    benefit_type: 'federal',
    target_groups: ['disability_1', 'disability_2', 'disability_3'],
    regions: [],
    applies_to_all_regions: true,
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    requirements: 'Наличие справки об инвалидности, индивидуальная программа реабилитации',
    how_to_get: 'Обратиться в органы социальной защиты с заявлением и документами',
    documents_needed: ['Справка об инвалидности', 'ИПР', 'Паспорт', 'Медицинское заключение'],
    source_url: 'https://mintrud.gov.ru/social/benefits/rehabilitation',
    last_verified: '2024-12-10',
    categories: [mockCategories[5]],
    views_count: 890,
    popularity_score: 8.0,
  },
]

export const mockCommercialOffers: CommercialOffer[] = [
  {
    id: 101,
    offer_id: 'apteka-36-6-2025',
    title: 'Скидка 15% на лекарства для пенсионеров',
    description: 'Скидка 15% на все лекарственные препараты для пенсионеров в сети аптек "36,6"',
    discount_percentage: 15,
    discount_description: '15% скидка на все лекарства',
    partner_name: 'Аптека 36,6',
    partner_category: 'Аптека',
    partner_website: 'https://366.ru',
    partner: {
      name: 'Аптека 36,6',
      category: 'Аптека',
      website: 'https://366.ru',
    },
    target_groups: ['pensioner'],
    regions: [mockRegions[0], mockRegions[1], mockRegions[2]],
    applies_to_all_regions: false,
    locations: [
      'г. Якутск, ул. Ленина, д. 10',
      'г. Якутск, пр. Ленина, д. 45',
      'г. Москва, ул. Арбат, д. 20',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    how_to_use: 'Предъявить пенсионное удостоверение при покупке в аптеке',
    promo_code: 'PENSION15',
    categories: [mockCategories[1]],
    views_count: 1250,
    popularity_score: 8.2,
  },
  {
    id: 102,
    offer_id: 'magnit-discount-2025',
    title: 'Скидка 10% на продукты для льготников',
    description: 'Скидка 10% на продукты питания в магазинах сети "Магнит" для льготных категорий граждан',
    discount_percentage: 10,
    discount_description: '10% скидка на продукты',
    partner_name: 'Магнит',
    partner_category: 'Магазин',
    partner_website: 'https://magnit.ru',
    partner: {
      name: 'Магнит',
      category: 'Магазин',
      website: 'https://magnit.ru',
    },
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'large_family', 'low_income'],
    regions: [mockRegions[0], mockRegions[1]],
    applies_to_all_regions: false,
    locations: [
      'г. Якутск, ул. Орджоникидзе, д. 15',
      'г. Якутск, ул. Курашова, д. 30',
      'г. Москва, ул. Тверская, д. 12',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    how_to_use: 'Предъявить удостоверение льготника на кассе при оплате',
    categories: [mockCategories[4]],
    views_count: 2100,
    popularity_score: 9.0,
  },
  {
    id: 103,
    offer_id: 'pharmacy-rigla-2025',
    title: 'Скидка 20% на витамины и БАДы',
    description: 'Скидка 20% на витамины, биологически активные добавки и товары для здоровья в аптеках "Ригла"',
    discount_percentage: 20,
    discount_description: '20% скидка на витамины и БАДы',
    partner_name: 'Ригла',
    partner_category: 'Аптека',
    partner_website: 'https://rigla.ru',
    partner: {
      name: 'Ригла',
      category: 'Аптека',
      website: 'https://rigla.ru',
    },
    target_groups: ['pensioner', 'disability_1', 'disability_2'],
    regions: [mockRegions[0], mockRegions[1], mockRegions[2]],
    applies_to_all_regions: false,
    locations: [
      'г. Якутск, ул. Дзержинского, д. 25',
      'г. Москва, ул. Новый Арбат, д. 8',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-06-30',
    status: 'active',
    how_to_use: 'Предъявить удостоверение льготника и назвать промокод при покупке',
    promo_code: 'VITAMIN20',
    categories: [mockCategories[1]],
    views_count: 980,
    popularity_score: 7.8,
  },
  {
    id: 104,
    offer_id: 'pyaterochka-discount-2025',
    title: 'Скидка 5% на все товары для многодетных семей',
    description: 'Скидка 5% на все товары в магазинах "Пятёрочка" для многодетных семей',
    discount_percentage: 5,
    discount_description: '5% скидка на все товары',
    partner_name: 'Пятёрочка',
    partner_category: 'Магазин',
    partner_website: 'https://5ka.ru',
    partner: {
      name: 'Пятёрочка',
      category: 'Магазин',
      website: 'https://5ka.ru',
    },
    target_groups: ['large_family'],
    regions: [mockRegions[0], mockRegions[1], mockRegions[2]],
    applies_to_all_regions: false,
    locations: [
      'г. Якутск, ул. Петра Алексеева, д. 5',
      'г. Якутск, ул. Ярославского, д. 18',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    how_to_use: 'Предъявить удостоверение многодетной семьи на кассе',
    categories: [mockCategories[4]],
    views_count: 1450,
    popularity_score: 8.5,
  },
  {
    id: 105,
    offer_id: 'mvideo-tech-2025',
    title: 'Скидка 7% на технику для ветеранов',
    description: 'Скидка 7% на бытовую технику и электронику в магазинах "М.Видео" для ветеранов',
    discount_percentage: 7,
    discount_description: '7% скидка на технику',
    partner_name: 'М.Видео',
    partner_category: 'Магазин техники',
    partner_website: 'https://mvideo.ru',
    partner: {
      name: 'М.Видео',
      category: 'Магазин техники',
      website: 'https://mvideo.ru',
    },
    target_groups: ['veteran'],
    regions: [mockRegions[0], mockRegions[1]],
    applies_to_all_regions: false,
    locations: [
      'г. Якутск, ТЦ "Туймаада", 2 этаж',
      'г. Москва, ул. Тверская, д. 10',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    how_to_use: 'Предъявить удостоверение ветерана при покупке',
    categories: [mockCategories[4]],
    views_count: 320,
    popularity_score: 6.5,
  },
  {
    id: 106,
    offer_id: 'beeline-discount-2025',
    title: 'Специальный тариф для пенсионеров от Билайн',
    description: 'Специальный тарифный план для пенсионеров с уменьшенной стоимостью услуг связи',
    discount_percentage: 30,
    discount_description: '30% скидка на тариф',
    partner_name: 'Билайн',
    partner_category: 'Оператор связи',
    partner_website: 'https://beeline.ru',
    partner: {
      name: 'Билайн',
      category: 'Оператор связи',
      website: 'https://beeline.ru',
    },
    target_groups: ['pensioner'],
    regions: [],
    applies_to_all_regions: true,
    locations: [],
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    how_to_use: 'Обратиться в салон связи Билайн с пенсионным удостоверением для подключения тарифа',
    categories: [mockCategories[7]],
    views_count: 1850,
    popularity_score: 8.8,
  },
  {
    id: 107,
    offer_id: 'mts-discount-2025',
    title: 'Льготный тариф МТС для инвалидов',
    description: 'Специальный тарифный план с уменьшенной стоимостью для инвалидов 1 и 2 группы',
    discount_percentage: 25,
    discount_description: '25% скидка на тариф',
    partner_name: 'МТС',
    partner_category: 'Оператор связи',
    partner_website: 'https://mts.ru',
    partner: {
      name: 'МТС',
      category: 'Оператор связи',
      website: 'https://mts.ru',
    },
    target_groups: ['disability_1', 'disability_2'],
    regions: [],
    applies_to_all_regions: true,
    locations: [],
    valid_from: '2025-01-01',
    valid_to: null,
    status: 'active',
    how_to_use: 'Обратиться в салон связи МТС со справкой об инвалидности',
    categories: [mockCategories[7]],
    views_count: 720,
    popularity_score: 7.2,
  },
  {
    id: 108,
    offer_id: 'domodedovo-taxi-2025',
    title: 'Скидка 10% на поездки в такси для льготников',
    description: 'Скидка 10% на поездки в такси "Домодедово" для льготных категорий граждан',
    discount_percentage: 10,
    discount_description: '10% скидка на поездки',
    partner_name: 'Такси Домодедово',
    partner_category: 'Транспортные услуги',
    partner_website: 'https://domodedovo-taxi.ru',
    partner: {
      name: 'Такси Домодедово',
      category: 'Транспортные услуги',
      website: 'https://domodedovo-taxi.ru',
    },
    target_groups: ['pensioner', 'disability_1', 'disability_2'],
    regions: [mockRegions[0], mockRegions[1]],
    applies_to_all_regions: false,
    locations: [],
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    how_to_use: 'При заказе такси через приложение или по телефону назвать промокод',
    promo_code: 'BENEFIT10',
    categories: [mockCategories[0]],
    views_count: 560,
    popularity_score: 6.8,
  },
  {
    id: 109,
    offer_id: 'leroy-merlin-2025',
    title: 'Скидка 8% на товары для ремонта для льготников',
    description: 'Скидка 8% на строительные материалы и товары для ремонта в гипермаркетах "Леруа Мерлен"',
    discount_percentage: 8,
    discount_description: '8% скидка на товары для ремонта',
    partner_name: 'Леруа Мерлен',
    partner_category: 'Строительный магазин',
    partner_website: 'https://leroymerlin.ru',
    partner: {
      name: 'Леруа Мерлен',
      category: 'Строительный магазин',
      website: 'https://leroymerlin.ru',
    },
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'veteran'],
    regions: [mockRegions[1], mockRegions[2]],
    applies_to_all_regions: false,
    locations: [
      'г. Москва, ул. Сходненская, д. 56',
      'г. Санкт-Петербург, пр. Энгельса, д. 157',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-12-31',
    status: 'active',
    how_to_use: 'Предъявить удостоверение льготника на кассе при оплате',
    categories: [mockCategories[4]],
    views_count: 420,
    popularity_score: 6.3,
  },
  {
    id: 110,
    offer_id: 'x5-retail-2025',
    title: 'Скидка 12% на продукты в сети "Перекрёсток"',
    description: 'Скидка 12% на продукты питания в магазинах "Перекрёсток" для льготных категорий',
    discount_percentage: 12,
    discount_description: '12% скидка на продукты',
    partner_name: 'Перекрёсток',
    partner_category: 'Магазин',
    partner_website: 'https://perekrestok.ru',
    partner: {
      name: 'Перекрёсток',
      category: 'Магазин',
      website: 'https://perekrestok.ru',
    },
    target_groups: ['pensioner', 'disability_1', 'disability_2', 'large_family', 'low_income'],
    regions: [mockRegions[0], mockRegions[1]],
    applies_to_all_regions: false,
    locations: [
      'г. Якутск, ул. Курашова, д. 42',
      'г. Москва, ул. Ленинградский проспект, д. 80',
    ],
    valid_from: '2025-01-01',
    valid_to: '2025-11-30',
    status: 'expiring_soon',
    how_to_use: 'Предъявить удостоверение льготника на кассе',
    categories: [mockCategories[4]],
    views_count: 1350,
    popularity_score: 8.0,
  },
]

